image: docker:27

services:
  - name: docker:27
    alias: docker

variables:
  DOCKER_FILE: $CI_PROJECT_DIR/Dockerfile
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
- build

build:
  stage: build
  variables:
    DOCKER_TAG: latest
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --file ${DOCKER_FILE} --tag ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
