variables:
  DOCKER_FILE: $CI_PROJECT_DIR/Dockerfile
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}

stages:
- build
- deploy

build:
  stage: build
  image:
    name: docker
  script:
  - docker build --file ${DOCKER_FILE} --tag ${DOCKER_IMAGE} .
  tags:
  - docker-image-builder


deploy:
  stage: deploy
  variables:
    DOCKER_TAG: latest
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
  - docker-image-builder
  dependencies:
  - build
