services:
  node-red:
    build: .
    entrypoint: /entrypoint.sh
    hostname: "nodered"
    environment:
      - TZ=Europe/Berlin
    ports:
      - 1880:1880
    volumes:
      - ../../containerData:/data
      - ../../villas-conf-node:/data/villas-conf-node
      - ./entrypoint.sh:/entrypoint.sh
      - /home/iko/Downloads/villasconfig.json:/tmp/villasconfig.json