version: "3.7"

services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "nodered"
    environment:
      - TZ=Europe/Berlin
    ports:
      - 1880:1880
    volumes:
      - ../../containerData:/data
      - ../../villas-conf-node:/villas-conf-node  