class ConfBuilder {
  constructor(jsonMsg) {
    this.config = {
      nodes: jsonMsg?.nodes || [],
      paths: jsonMsg?.paths || [],
      http: jsonMsg?.http,
      logging: jsonMsg?.logging,
      stats: jsonMsg?.stats,
      affinity: jsonMsg?.affinity,
      priority: jsonMsg?.priority,
      hugepages: jsonMsg?.hugepages,
    };
  }

  validate() {
    //easy check all global confs
    // if (!this.config.stats || !isFloat(this.config.stats)) return false;
    // if (!this.config.affinity || !isInt(this.config.affinity)) return false;
    // if (!this.config.priority || !isInt(this.config.priority)) return false;
    // if (!this.config.hugepages || !isInt(this.config.hugepages)) return false;
    //TODO: continue with checking http
    //TODO: continue with checking logging
    //TODO: continue with checking nodes
    //TODO: continue with checking paths
  }

  addNode(name, config) {
    // if (!name || typeof name === "string")
    //   throw ValidationError("Name required of type string");
    //
    // if (name in this.config.nodes) {
    //   throw Error("name already defined");
    // }
    //
    //TODO: further validation on types
    //validate(config)

    this.config.nodes[name] = config;
  }

  /**
   * `build` builds the json configuration generated by this builder.
   * @returns A (partial) villas configuration
   */
  build() {
    const replacer = (_, value) => {
      // Filtering out properties
      if (!value) {
        return undefined;
      }
      return value;
    };

    return JSON.stringify(this.config, replacer);
  }

  print() {
    console.log("Generated json", this.config);
  }
}

module.exports = {
  ConfBuilder: ConfBuilder,
};
